//
//  SODConstants.m
//  SOD.iOS
//
//  Created by Project BJ on 12. 5. 25..
//  Copyright (c) 2012년 __MyCompanyName__. All rights reserved.
//

#import "SODConstants.h"

@implementation SODConstants
@synthesize DATATYPE_INT, DATATYPE_FLOAT, DATATYPE_DOUBLE, DATATYPE_STRING,DATATYPE_BYTEARRAY;
@synthesize REQUEST_ACCEPT, RESPONSE_ACCEPT, REQUEST_PING, RESPONSE_PING, RESPONSE_SERVICE_NAME, REQUEST_CLIENT_ALIVE, RESPONSE_CLIENT_ALIVE, REQUEST_SERVICE_DATA, RESPONSE_SERVICE_DATA;

-(id)init
{
    DATATYPE_INT = @"int";
    DATATYPE_FLOAT = @"float";
    DATATYPE_DOUBLE = @"double";
    DATATYPE_STRING = @"string";
    DATATYPE_BYTEARRAY = @"bytearray";
    
    REQUEST_ACCEPT = 0xFF000010;
    RESPONSE_ACCEPT = 0xFF000011;
    REQUEST_PING = 0xFF000020;
    RESPONSE_PING = 0xFF000021;
    RESPONSE_SERVICE_NAME = 0xFF000000;
    REQUEST_CLIENT_ALIVE = 0xFF000001;
    RESPONSE_CLIENT_ALIVE = 0xFF000002;
    REQUEST_SERVICE_DATA = 0xFF000003;
    RESPONSE_SERVICE_DATA = 0xFF000004;
    
    return self;

}
@end
